### ISSUE TITLE
OpenPaaSTA_플랫폼_설치자동화_aws_install_guide.docx중 질문

### ISSUE THREAD

**Issue by gabilim1002** [OpenPaaSRnD/Documents#10]
OpenPaaSTA_플랫폼_설치자동화_aws_install_guide.docx중 질문

3.1 플랫폼 설치 자동화 설치 메뉴 하위
4 플랫폼 설치 자동화 실행
$ java -jar -Djava.security.egd=file:/dev/./urandom -Dspring.config.location=./application.properties target/OPENPAAS-IEDA-WEB-1.0.0-SNAPSHOT.jar

위의 OPENPAAS-IEDA-WEB-1.0.0-SNAPSHOT.jar application을 찾을 수가 없습니다.
아래의 다운로드 링크에서 OPENPAAS-IEDA-WEB.zip을 받아서 설치 진행 중입니다.

https://github.com/OpenPaaSRnD/Documents/blob/master/Download_Page.md

도움 부탁드립니다.

**Comment by doraKim** [comment]
application.properties 파일은
OPENPAAS-IEDA-WEB/src/main/resource/application.properties
에 있습니다.
해당 파일을 OPENPAAS-IEDA-WEB 디렉토리 아래에 복사 후, 수정하여 사용하시면 됩니다.
자세한 내용은 3.1절의 3번에 자세히 기술되어 있습니다.

 OPENPAAS-IEDA-WEB-1.0.0-SNAPSHOT.jar 은
maven 컴파일이 성공하면 생성됩니다.
자세한 내용은 3.1절의 4번에 자세히 기술되어 있습니다.



2016-12-29 8:31 GMT+09:00 gabilim1002 <notifications@github.com>:

**Comment by gabilim1002** [comment]
빠른 확인 감사합니다. ^^

MAVEN설치 진행 후
mvn -Djava.security.egd=file:/dev/./urandom -Dspring.config.location=./application.properties  package


com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.

위와 같이 드라이버가 패킷을 받지 못했다는 메시지가 표시가 됩니다.
톰캣의 보안 설정으로 문제가 되는것으로 확인되는데(/etc/tomcat/policy.d/04webapps.policy) 
별도로 톰캣을 설치 해서 진행을 해야 하나요?
아니면 위에 해당하는 문제를 해결 할 수 있는 방법이 따로 있나요?

감사합니다.

**Comment by doraKim** [comment]
본 설치 자동화 시스템은 spring boot 기반으로 개발 되었으므로 별도의 tomcat 서버는 필요하지는 않습니다.

설치 및 구성 환경이 가이드와 일치 하지 않은 것으로 보여 정확한 답변을 드리기 어렵습니다만,

아래의 링크에 나와있는 방법을 참고 해 보시길 바랍니다.

http://stackoverflow.com/questions/6865538/solving-a-communications-link-failure-with-jdbc-and-mysql





2016-12-29 9:15 GMT+09:00 gabilim1002 <notifications@github.com>:

**Comment by gabilim1002** [comment]
문제 확인 결과 mysql 설정 문제 였네요....

권한 설정
GRANT ALL PRIVILEGES ON *.* to root@localhost IDENTIFIED BY '777888999' WITH GRANT OPTION; 
flush privileges;

mysqld.conf에서bind설정 변경 후 restart
bind-address            = 0.0.0.0


위 적용 후 정상적으로 빌드 되서 설치 화면 뜹니다.^^
