### ISSUE TITLE
PaasTA의 controller 배포시 에러에 대한 문의

### ISSUE THREAD

**Issue by baum1982** [OpenPaaSRnD/Documents#4]
PaasTA의 controller 배포시 아래와 같은 에러가 발생합니다.
gorouter  패키지 배포시 컴파일 중  segmentation fault  에러가 발생합니다.

bosh task의 전체 로그를 첨부하오니 의견 부탁드립니다.

```
E, [2016-11-03 07:04:15 #9020] [task:6] ERROR -- DirectorJobRunner: Action Failed get_task: Task e26fec73-fd91-439a-566a-77a44b6b0f49 result: Compiling package gorouter: Running packaging script: Command exited with 1; Stdout: , Stderr: + REPO_NAME=github.com/cloudfoundry/gorouter
+ REPO_DIR=/var/vcap/packages/gorouter/src/github.com/cloudfoundry/gorouter
++ dirname /var/vcap/packages/gorouter/src/github.com/cloudfoundry/gorouter
+ mkdir -p /var/vcap/packages/gorouter/src/github.com/cloudfoundry
+ cp -a github.com/cloudfoundry/gorouter/ /var/vcap/packages/gorouter/src/github.com/cloudfoundry/gorouter
++ readlink -nf /var/vcap/packages/golang1.4
+ export GOROOT=/var/vcap/data/packages/golang1.4/714698bc352d2a1dbe321376f0676037568147bb.1-6f20ff14a852546b0eb779dcb5d61821e1aa6d88
+ GOROOT=/var/vcap/data/packages/golang1.4/714698bc352d2a1dbe321376f0676037568147bb.1-6f20ff14a852546b0eb779dcb5d61821e1aa6d88
+ export GOPATH=/var/vcap/packages/gorouter:/var/vcap/packages/gorouter/src/github.com/cloudfoundry/gorouter/Godeps/_workspace
+ GOPATH=/var/vcap/packages/gorouter:/var/vcap/packages/gorouter/src/github.com/cloudfoundry/gorouter/Godeps/_workspace
+ export PATH=/var/vcap/data/packages/golang1.4/714698bc352d2a1dbe321376f0676037568147bb.1-6f20ff14a852546b0eb779dcb5d61821e1aa6d88/bin:/var/vcap/bosh/bin:/usr/local/bin:/usr/local/sbin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/X11R6/bin
+ PATH=/var/vcap/data/packages/golang1.4/714698bc352d2a1dbe321376f0676037568147bb.1-6f20ff14a852546b0eb779dcb5d61821e1aa6d88/bin:/var/vcap/bosh/bin:/usr/local/bin:/usr/local/sbin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/X11R6/bin
+ go install github.com/cloudfoundry/gorouter
go build github.com/cloudfoundry/gorouter: /var/vcap/data/packages/golang1.4/714698bc352d2a1dbe321376f0676037568147bb.1-6f20ff14a852546b0eb779dcb5d61821e1aa6d88/pkg/tool/linux_amd64/6l: signal: segmentation fault
```

[에러로그.zip](https://github.com/OpenPaaSRnD/Documents/files/568459/default.zip)

**Comment by changhaksong** [comment]
안녕하십니까.

에러로그를 보니 bosh 의 Director 와 controller 설치시 사용하는 stemcell과의 통신이 되지 않는것 같습니다. 

먼저 openstack 의 horizon 에 접속 하셔서 다시 한번 security group 를 확인해주시고 controller 에서 만들어지는 vm 과 bosh director 와 통신이 가능하게 네트웍이 구성되어 있는지 확인 해주십시요.

그리고 설치 파일을 보니 도메인을 controller.open-paas.com 으로 하셨는데요. 
dns 에서 해당 도메인으로 접속할수 있게 되어 있나요? 
그리고 ssl_pem 정보를 controller.open-paas.com 으로 접속할수 있게 만들어서 넣었는지도 확인 부탁 드립니다. 
controller.open-paas.com 에 대한 dns 세팅은 위의 compile 에러와는 상관이 없지만 controller 설치중에 job 업데이트시 에러가 날수 있고 설치가 되더라고 login 이 되지 않습니다. 

다시 한번 확인후 답변 주시면 감사하겠습니다.

**Comment by chonh** [comment]
안녕하십니까? 우선 답변 감사드립니다.

첫째, 위 에러는 bosh deploy 를 통한 controller 배포시 다른 패키지 컴파일은 정상적으로 완료되었고,
gorouter 패키지 컴파일 진행중에 발생한 것입니다. 보안 그룹 및 네트웍 통신은 재차 확인하였고,
현재 bosh director와 controller vm간 통신은 잘되고 있습니다.  gorouter 패키지 컴파일 에러에 대한 다른 이유가 있는 건 아닌지 궁금합니다. 

둘째, ssl_pem 정보는 인증서 및 개인키를 생성하여 openpaas controller 샘플 yml 파일에 복사해 넣은 상태이며,  가이드를 참고하여 제공해주신 openpaas controller 샘플 yml에 별도 vm 인스턴스를 생성하여 DNS 서버를 구성한 환경 정보들을 셋팅한 결과입니다. (상기 도메인명은 HA Proxy ip로 등록하였습니다.)

마지막에 Job 업데이트시 에러가 발생할 수 있다고 말씀하였는데 이에 대해 추가적으로 해야 하는 세팅이 나 조치사항이 있나요?
추가 설명 부탁드리겠습니다.

**Comment by changhaksong** [comment]
안녕하세요. 

첫번째 부분은 저희쪽에서 goruter  만 컴파일이 안된적이 없어서요. 
설치하신 릴리지 버전으로 저희가 설치를 다시 해보고 답변을 드리겠습니다. 

둘째 부분은 인증서 생성해서 만들어서 넣었으면 다른 이슈 없이 잘 됩니다. 

이상입니다.

**Comment by changhaksong** [comment]
안녕하세요.

저희쪽에서 다시 설치 해보았지만 에러 없이 잘 설치가 되었습니다. 

첫번째 주신 로그 zip 파일을 보니 거의 맨 아래 부분을 보니 아래와 같이 404 에러가 납니다. 

controller:8774">>>>>>}
D, [2016-11-03T07:04:15.478004 #9180] DEBUG -- : excon.error {:error=>#<Excon::Errors::NotFound: Expected([200, 203]) <=> Actual(404 Not Found)
excon.error.response
  :body          => "{\"itemNotFound\": {\"message\": \"Instance 56485941-a433-4878-a8ac-52ccba4d79bf could not be found.\", \"code\": 404}}"
  :headers       => {
    "Content-Length"       => "111"
    "Content-Type"         => "application/json; charset=UTF-8"
    "Date"                 => "Thu, 03 Nov 2016 07:04:17 GMT"
    "X-Compute-Request-Id" => "req-d585dfb7-3d68-4934-b07e-f857c913245a"
  }
  :local_address => "10.20.0.62"
  :local_port    => 40742
  :reason_phrase => "Not Found"
  :remote_ip     => "192.168.0.200"
  :status        => 404
  :status_line   => "HTTP/1.1 404 Not Found\r\n"
>}

D, [2016-11-03 06:40:15 #9020] [compile_package(loggregator_trafficcontroller/6224f7a220924182b376e43b791ceda9750adff8, bosh-openstack-kvm-ubuntu-trusty-go_agent/3147)] DEBUG -- DirectorJobRunner: External CPI got response: {"result":"56485941-a433-4878-a8ac-52ccba4d79bf","error":null,"log":""}, err: D, [2016-11-03T06:40:07.033367 #9043] DEBUG -- : excon.request {:chunk_size=>1048576, :ciphers=>"HIGH:!SSLv2:!aNULL:!eNULL:!3DES", :connect_timeout=>60, :debug_request=>false, :debug_response=>true, :headers=>{"User-Agent"=>"fog/1.34.0 fog-core/1.32.1", "Content-Type"=>"application/json", "Host"=>"192.168.0.200:5000"}, :idempotent=>false, :instrumentor_name=>"excon", :middlewares=>[Excon::Middleware::ResponseParser, Excon::Middleware::Expects, Excon::Middleware::Idempotent, Excon::Middleware::Instrumentor, Excon::Middleware::Mock], :mock=>false, :nonblock=>true, :omit_default_port=>false, :persistent=>false, :read_timeout=>60, :retry_limit=>4, :ssl_verify_peer=>true, :tcp_nodelay=>false, :thread_safe_sockets=>true, :uri_parser=>URI, :versions=>"excon/0.45.4 (x86_64-linux) ruby/2.1.7", :write_timeout=>60, :host=>"192.168.0.200", :hostname=>"192.168.0.200", :path=>"/v2.0/tokens", :port=>5000, :query=>nil, :scheme=>"http", :instrumentor=>Bosh::OpenStackCloud::ExconLoggingInstrumentor, :expects=>[200, 204], :body=>"{\"auth\":{\"passwordCredentials\":{\"username\":\"demo\",\"password\":\"DEMO_PASS\"},\"tenantName\":\"demo\"}}", :method=>"POST", :retries_remaining=>4, :connection=>#<Excon::Connection:7fa0ca0eba38 @data={:chunk_size=>1048576, :ciphers=>"HIGH:!SSLv2:!aNULL:!eNULL:!3DES", :connect_timeout=>60, :debug_request=>false, :debug_response=>true, :headers=>{"User-Agent"=>"fog/1.34.0 fog-core/1.32.1"}, :idempotent=>false, :instrumentor_name=>"excon", :middlewares=>[Excon::Middleware::ResponseParser, Excon::Middleware::Expects, Excon::Middleware::Idempotent, Excon::Middleware::Instrumentor, Excon::Middleware::Mock], :mock=>false, :nonblock=>true, :omit_default_port=>false, :persistent=>false, :read_timeout=>60, :retry_limit=>4, :ssl_verify_peer=>true, :tcp_nodelay=>false, :thread_safe_sockets=>true, :uri_parser=>URI, :versions=>"excon/0.45.4 (x86_64-linux) ruby/2.1.7", :write_timeout=>60, :host=>"192.168.0.200", :hostname=>"192.168.0.200", :path=>"/v2.0/tokens", :port=>5000, :query=>nil, :scheme=>"http", :instrumentor=>Bosh::OpenStackCloud::ExconLoggingInstrumentor} @socket_key="http://192.168.0.200:5000">, :stack=>#<Excon::Middleware::ResponseParser:0x007fa0ca0cc570 @stack=#<Excon::Middleware::Expects:0x007fa0ca0cc598 @stack=#<Excon::Middleware::Idempotent:0x007fa0ca0cc5c0 @stack=#<Excon::Middleware::Instrumentor:0x007fa0ca0cc5e8 @stack=#<Excon::Middleware::Mock:0x007fa0ca0cc610 @stack=#<Excon::Connection:7fa0ca0eba38 @data={:chunk_size=>1048576, :ciphers=>"HIGH:!SSLv2:!aNULL:!eNULL:!3DES", :connect_timeout=>60, :debug_request=>false, :debug_response=>true, :headers=>{"User-Agent"=>"fog/1.34.0 fog-core/1.32.1"}, :idempotent=>false, :instrumentor_name=>"excon", :middlewares=>[Excon::Middleware::ResponseParser, Excon::Middleware::Expects, Excon::Middleware::Idempotent, Excon::Middleware::Instrumentor, Excon::Middleware::Mock], :mock=>false, :nonblock=>true, :omit_default_port=>false, :persistent=>false, :read_timeout=>60, :retry_limit=>4, :ssl_verify_peer=>true, :tcp_nodelay=>false, :thread_safe_sockets=>true, :uri_parser=>URI, :versions=>"excon/0.45.4 (x86_64-linux) ruby/2.1.7", :write_timeout=>60, :host=>"192.168.0.200", :hostname=>"192.168.0.200", :path=>"/v2.0/tokens", :port=>5000, :query=>nil, :scheme=>"http", :instrumentor=>Bosh::OpenStackCloud::ExconLoggingInstrumentor} @socket_key="http://192.168.0.200:5000">>>>>>}


192.168.0.200, 10.20.0.62 VM 에는 무엇이 설치 되어 있나요?? 

그리고 현재 설치 되어있는 OpenStack 버전은 어떻게 되나요??

OpenStack 과 PaaS-TA OpenStack CPI 와 설정이 안맞는거 같습니다.

확인 부탁 드립니다.

**Comment by baum1982** [comment]
답변 감사합니다.

192.168.0.200는 OpenStack Liberty 버전의  Controller  노드의 IP  이고,
10.20.0.62는 Bosh  VM 의 IP입니다.

Bosh  VM 에서 OpenStack  Controller 노드의 네트워크 접근은 문제 없는 것으로 확인 되었습니다.
40742 포트를 사용하는 통신의 문제로 보이는데 두 서버 모두 40742  포트를 사용하는 프로세스는 실행되어 있지 않습니다.

40742 포트  사용에 대한 의견 있으시면 도움 주시기 바랍니다.

**Comment by baum1982** [comment]
본 에러는 OCP팀에서 제공해준  Controller Release 파일  내 golang1.4 package가 gorouter package와 dependancy가 있는 것으로 추측되며, gorouter package 컴파일 작업중 segmentation fault 에러가 발생한 것으로 보입니다.
기술지원을 해준 BD(블루다임) 측에서 제공해준 비공식 Controller Release 파일은 golang 1.5/1/6 package로 구성되어 있어서 이 Release로 배포해본 결과 gorouter package 컴파일 작업이 정상 완료되었습니다.
