### ISSUE TITLE
PaaS-TA Container 설치시 diego 관련 plug-in 설치 여부

### ISSUE THREAD

**Issue by chonh** [OpenPaaSRnD/Documents#5]
PaaS-TA Container 설치 가이드를 보면 예전 beta 버전에 있었던 diego 관련 plug-in 설치는 
빠져 있습니다. PaaS-TA 버전에서는 diego 컨테이너를 활용하여 어플리케이션 배포시 플러그인 설치가 필요 없게 된건가요? 아님 누락이 된건가요?
```
beta)
$ cf install-plugin https://github.com/cloudfoundry-incubator/diego-cli-plugin/raw/master/bin/linux64/diego-beta.linux64
```

**Comment by doraKim** [comment]
PaaS-TA  버전에서는 Controller, Container의 배포 manifest.yml 에서 플러그인에서 처리 할 내용에 대해 설정을 하여 배포하기 때문에 별도 플러그인 설치가 필요 없습니다.

**Comment by chonh** [comment]
감사합니다.
