### ISSUE TITLE
PaaS_TA Controller 설치 검증 오류

### ISSUE THREAD

**Issue by baum1982** [OpenPaaSRnD/Documents#7]
PaaS_TA Controller의 설치검증 과정에서 문제가 발생하여 질문 드립니다

deply는 성공하여 아래와 같이 admin 계정으로 정상적으로 로그인이 됩니다 
![image](https://cloud.githubusercontent.com/assets/1538568/20741633/eda2af1c-b70e-11e6-8ba0-be3dbc690ac1.png)

하지만 Sample Application 배포 시 아래와 같은 권한 오류가 발생합니다
![image](https://cloud.githubusercontent.com/assets/1538568/20741757/8fa68e46-b70f-11e6-97a4-2bc147fcb04d.png)

아래와 같이 OCP Org의 권한을 확인 해 보니 권한을 가진 사용자가 없었습니다
![image](https://cloud.githubusercontent.com/assets/1538568/20742085/7fc210fc-b711-11e6-88ea-991cd87c9dd9.png)

admin  계정으로 OCP Org에 대한  권한을 부여하기 위에 다음과 같이 Role을 할당하는 과정에서도 오류가 발생 합니다
![image](https://cloud.githubusercontent.com/assets/1538568/20741720/68505318-b70f-11e6-8340-42a4f0d54d65.png)

설치 가이드 상에서 누락된 권한 관련 설정이 혹시 있다면 정보를 공유해 주기기 바랍니다.

**Comment by changhaksong** [comment]
안녕하십니까.

위의 경우는 PaaS-TA 설치시 생성되는 VM에서 *.controller.open-paas.com 으로 다른 VM 으로 통신을 못하는 경우 입니다. 
예를 들어서 api_z1  VM 에서 uaa_z1 VM 으로 API로 통신시 uaa.controller.open-paas.com 으로 API를 호출합니다. 
DNS 설치후 설정 정보중에 *.controller.open-paas.com 으로 오는 것을 세팅한 IP로 전송하는데요. 
설정한 IP로 VM 간에 통신이 가능하지 못할 경우 위의 같은 오류가 납니다. 또는 VM 상에서 domain을 NSLookup 을 못할 경우입니다. 

그러니 우선 api_z1 VM 에 들어가셔서 NSLOOKUP 으로 DNS Server에 *.controller.open-paas.com Domain이 정상 적으로 접근이 되는지 확인하시기 바랍니다.

해당 IP 와 포트 가 접근가능하게 OpenStack security group이 설정 되어 있는지 확인해 주십시요.

**Comment by baum1982** [comment]
답변 감사합니다
admin의 권한 문제는 덕분에 해결을 하였으나 application 을 Push  하는 과정에서 아래와 같은 오류가 발생합니다
'CF_TRACE=true ' 옵션을 활용하여 상세 내용을 보니 Push 이후 Application을 시작 하는 도중 문제가 발생하는 듯 합니다.

의견 부탁드립니다

![image](https://cloud.githubusercontent.com/assets/1538568/20744257/4ab6bc8e-b71e-11e6-85b1-c7399be4dffc.png)




```
Starting app hello-tomcat-spring-test in org OCP / space dev as admin...

REQUEST: [2016-11-30T16:52:06+09:00]
PUT /v2/apps/15c3a434-d3c5-47dc-9f9d-dab2836e5556?async=true&inline-relations-depth=1 HTTP/1.1
Host: api.controller.open-paas.com
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Content-Type: application/json
User-Agent: go-cli 6.14.1+dc6adf6 / linux

{"state":"STARTED"}

RESPONSE: [2016-11-30T16:52:06+09:00]
HTTP/1.1 500 Internal Server Error
Content-Length: 99
Content-Type: application/json;charset=utf-8
Date: Wed, 30 Nov 2016 07:52:05 GMT
Server: nginx
X-Cf-Requestid: bbf2507f-f120-46c7-4f8a-990c1654356c
X-Content-Type-Options: nosniff
X-Vcap-Request-Id: dec56f6c-8094-4538-5de4-d94880c3a6f2::ebfb42af-9f53-43d2-800a-467a56c47e6a

{
  "error_code": "UnknownError",
  "description": "An unknown error occurred.",
  "code": 10001
}

FAILED
Server error, status code: 500, error code: 10001, message: An unknown error occurred.
FAILED
Server error, status code: 500, error code: 10001, message: An unknown error occurred.

```
